FrancescoXX/free-Web3-resources

README.md
Hi Francesco, I have removed the table of contents.
=> Removing Table of contents

README.md, index.html
Created a live version of the resources, you can view the demo here: https://suhailkakar.github.io/free-Web3-resources/
closes #17
You can use GitHub pages and choose the main branch, it should automatically deploy the website :)
https://user-images.githubusercontent.com/56798748/162453760-ecb9888d-ccf7-40ce-a60c-63cbc512e6cd.mov
EDIT: I will be adding new plugins such search functionality and etc in the future :)
=> Created a live version of the list

README.md
=> add Odyssey DAO to DAO Communities category

index.html
I have added a search option to the live version, so the users can directly search for any resources they want : )
https://user-images.githubusercontent.com/56798748/163710577-79002e2a-070f-4dc7-9405-496f8e7a777d.mov
=> Added search option

README.md
- I added foundry to the Ethereum Development Environment section.
=> Foundry added to Development Environment

README.md
The following resources have been added to their respective sections:
- WebXDAO, An Open Source Community that focuses on decentralized applications, web 3, and blockchain technologies 🚀
- Oasis, A privacy-enabled blockchain platform for open finance and a responsible data economy.
Plus, there was `(3)` in the alt text of the banner, which was unnecessary. Thus, removed.
=> docs: addition of resources to the list

README.md
new section solana has been added with following section:
- tutorials
=> adding Solana Section

README.md
added credit for Vittorio Rivabella
Closes #7  I will add more soon and create another PR with a bunch of credited sources.
Added credits for  Vittorio Rivabellax
=> Added Credits

CONTRIBUTING.md
=> docs: add a contributing guide

README.md
What do we think to adding some tutorials under Solidity? 
- Added 'Tutorials' section under 'Solidity'
- Added a new Solidity tutorial from FreeCodeCamp and description
=> Added a Solidity tutorial from FreeCodeCamp

README.md
=> Add Harmony blockchain

README.md
Add [Chainstack](https://chainstack.com/) as a node provider.
Change the "Brazilian" language to Portuguese. (Brazilian doesn't really exists😄)
- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.
=> Added Chainstack as node provider and changed Brazilian language to Portuguese

README.md
Added a new Section For Learning Platforms and added some Platform links.
=> Added a learning Platform with one platform link

README.md
Closes Issue #58 
Added a link for beginners looking forward to Full Stack Ethereum Development.
=> Added a Free Resource Link.

README.md
Closes #32 
The **free-Web3-resources** list is now sorted by alphabetical order.
Hi! 👋🏻
=> docs: sort the list by alphabetical order

README.md
=> fix link to learnweb3

README.md
this pull request Adds Ethereum development resources. 
closes #68
Addition of Ethereum development resources
=> Add Feature Ethereum Development Resources

README.md
The following resources have been added to their respective sections:
- web3 journey by eda
- swarm in file stroage section
=> adding web3 journey by eda and swarm in file storage sec

README.md
- Add the YT Channel of [EatTheBlocks](https://www.youtube.com/c/EatTheBlocks) in `README.md` file
Kindly review it and merge my PR. I'd be happy to contribute to this repository as my first step while getting into the world of Web3. This is under Hacktoberfest contribution.
=> [DOCUMENTATION] Add new YT channel in README

README.md
Closes #87 
Please add hacktoberfest label
Added Nader Dabit, Block Explorer YT Channels
Added Javascript Mastery Roadmap for Web3
=> Added 2 new YT Channels and 1 new Roadmap

.github/workflows/release.yml
Release file added in .github/workflows/
=> Release dot yaml file added

README.md
Closes #102 
Added more video roadmaps
And separated video and text roadmap
=> Separated Text & Video Roadmaps and added more video roadmaps

README.md
closes #103 
Added Hindi section to the README
- [x ] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.
=> Add Hindi section to README

README.md
Closes #97 
Added cryptozomboes
=> Add cryptozombies

README.md
Closes #108 
Added Vyper Section
=> Added Vyper Section

README.md
closes #88 
add new section (in person presentation section)
=> add new section (in person presentation section)

README.md
#118 
Added new roadmap
Please add hacktoberfest labels
=> Added new roadmap

FREE Web3 Resources (2).html, README.md
=> add solidity resource

index.html
- Fixed issue with favicons not displaying
Related but different corrective actions
https://github.com/FrancescoXX/free-Web3-resources/issues/123
=> fix favicon

index.html
https://github.com/FrancescoXX/free-Web3-resources/pull/149/commits/8a1f2f4c8ba58a6fa44a4619b268683f306b5355 this was the commit that caused the conflict due to auto-merge, which caused script failure and dark mode was not working.
fixing merge conflict due to this commit https://github.com/FrancescoXX/free-Web3-resources/pull/149/commits/8a1f2f4c8ba58a6fa44a4619b268683f306b5355
=> fixing conflict caused by last commit

README.md
Added a new youtube channel "Clever Programmer"
=> Add youtube channel

README.md
- Added the Patrick Collins Youtube Channel in Youtube Channels list.
We are gathering web3 resources so how can we forget to add Patrick Collins's Channel to the YouTube Channels list?
=> Add Patrick Collins YouTube Channel

README.md
- Removing an extra bullet from **Web3 Roadmaps (Article / Blog)**.
- Fixed ## for a line.
=> Minor Fixes in README

FREE Web3 Resources (2).html, README.md
Added Web3 Foundation Youtube Channel in FREE Web3 Resources(2).html
=> Added Web3 Foundation youtube channel link in readme file

README.md
=> Added Elrond blockchain

README.md
Added a blockchain Raodmap by Clever Programmer, closes Issue #126 
Adding a new resource for Blockchain roadmap in video resources section of the readme.
=> Blockchain Roadmap added.

README.md
removed youtube sections which is written twice and also removed the resources in identity section which were same in Ethereum development tools
=> remove repeated sections

README.md
=> Removed Vietnamese section.

code-snippets/ERC20Token.sol, code-snippets/readme.md
Added Code-Snippets folder with a "readme" file and a smart contract to mint an ERC20 Token.
=> Code snippets

README.md
Closes #185 
- Added a GitHub icon next to the main heading
- It redirects back to the repo
Please check if changes apply to the website
=> add GitHub icon that redirects to repository

README.md
some helpful web3 resources were are like create-eth-app , Embark, and BlockTrain
- [ x ] My code follows the code style of this project.
- [ x ] This PR does not contain plagiarized content.
- [ x ] The title of my pull request is a short description of the requested changes.
=> Resources added

code-snippets/ERC721Token.sol
ERC721 snippet added to create NFTs smart contract
- [ x ] My code follows the code style of this project.
- [ x ] This PR does not contain plagiarized content.
- [ x ] The title of my pull request is a short description of the requested changes.
=> ERC721 snippet added

README.md
Made the correction using grammarly tool
Closes #198
Made all the grammar checks and word usage to make it to world standards
Grammarly check score:
=> Grammer and word usage correction

README.md
=> Added the Youtube Channel Description

README.md
Solved #208 issue.
pls add hacktoberfest-accepted as well
=> Updated Description of Web3 Roadmaps

README.md
=> Add Description on Open Source projects 1/2

README.md
Added the Hardhat Starter Kit in the Ethereum Development Tools section.
I have added the hardhat-starter-kit to the Ethereum Development Tools section.
About Kit: Hardhat Starter Kit is a repo for boilerplate code for testing, deploying, and shipping chainlink solidity code.
=> Add Hardhat Starter Kit

README.md
Add the Foundry Starter Kit in the Ethereum Development Tools section
Added the Foundry Starter Kit in the Ethereum Development Tools section.
About Foundry: Foundry Starter Kit is a repo that shows developers how to quickly build, test, and deploy smart contracts with one of the fastest frameworks out there
=> Add Foundry Starter Kit

code-snippets/Transactions.sol
Transaction snippet added
- [ x ] My code follows the code style of this project.
- [ x ] This PR does not contain plagiarized content.
- [ x ] The title of my pull request is a short description of the requested changes.
=> Transaction snippet added

code-snippets/ERC1155Token.sol
Added Contract For ERC1155 Token
Added Contract For ERC1155 Token
- [x ] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
=> fea: Add ERC1155Token.sol

README.md
Added new blockchain resources
Added Binance Academy platform as a resource to get into web3
- [ x] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
=> feat: Update Readme.md

README.md
Closes #230
These resources are listed twice in the README under the Solana section:
[Complete Guide to Full Stack Solana Development by Nader Dabit](https://dev.to/edge-and-node/the-complete-guide-to-full-stack-solana-development-with-react-anchor-rust-and-phantom-3291)
[How to Mint an NFT on Solana](https://www.quicknode.com/guides/web3-sdks/how-to-mint-an-nft-on-solana)
This PR removes the duplicates
=> Removed duplicates under Solana section

README.md
ethereum.org in different languages was not looking good
=> hindi roadmap and some minor changes in ethereum.org in different languages

README.md
=> Update Hindi Web3 youtube channel

README.md
=> add a polygon section

README.md
This PR resolves #237 
@FrancescoXX , you can merge now :)
#HAPPYCODING
=> Added index on README.md

README.md
=> Added descriptions on Solana Articles

README.md
Closes #263 
* just add an amazing blockchain course in Urdu language link in the documentation.
* improve heading.
=> Add amazing blockchain course in urdu language youtube channel link.

code-snippets/PiggyBank.sol
Closes #246 
add piggy bank code in solidity in which users can save their money and when they withdraw, the contract will self-destroy like a conventional piggy bank.
Thanks for giving me a chance to contribute.
=> add piggy bank code in solidity

code-snippets/EnglishAuction.sol
Closes #248 
* Add English auction code in the code snippets folder
Thanks for giving me an opportunity to contribute.
=> Add English Auction Code in Solidity

code-snippets/Weth.sol
Closes #247 
* add wrapped eth contract in solidity.
Thanks for giving me an opportunity to contribute.
=> create wrapped eth contract in solidity

FREE Web3 Resources (2).html, README.md
Closes #257
I want to add https://www.kachingnft.io/ as one of the NFT marketplace, it is NFT marketplace specialized in gaming and using Seaport as the base.
=> feat: add kaching nft marketplace

README.md
Add emoji to heading in readme.md
=> Added a emoji to heading in Readme.md

README.md
Closes #268
- Fix link back to top
=> fix: link back to top

README.md
Removed Duplicate oracle and off chain data protocol section
=> Removed Duplicate sections

blockchainArchitecture.md
- Adds a markdown file on Blockchain Architecture
- Markdown contains link to an external detailed publication on Monolithic and Modular Blockchains
Modular blockchain approach aids further understanding from the blockchain trilemma standpoint. <br>
I saw a detailed review on blockchain trilemma right here on the repository, it spurred me into sharing my publication on modular blockchains. 
This will indeed be a great material for anyone seeking to start out learning about blockchains and web3.0
=> Docs add blockchain architecture modular monolithic

README.md
PUSH Protocol (EPNS) is the world’s first decentralized notification protocol for Web3.
Using the protocol, any smart contract, dApp, or backend service can send on-chain or off-chain notifications tied to the wallet addresses of users in a gasless, multichain, open, and platform-agnostic way.
Being an open communication middleware, notifications can be integrated and shown on any crypto wallet, mobile app, browser extension, or dApps, enabling a native communication layer for Web3.0
=> Add Push Protocol 

README.md
Added Roadmap by EatTheBlocks
Added Roadmap by Dapp University
=> Updated README.md (Added two video Roadmaps)

README.md
[Flow](https://flow.com/) Flow is a fast, secure, and developer-friendly blockchain built for games, apps, and digital assets.
Closes https://github.com/FrancescoXX/free-Web3-resources/issues/145
added "[Flow](https://flow.com/) Flow is a fast, secure, and developer-friendly blockchain built for games, apps, and digital assets."
not needed
=> added flow in blockchain section

README.md
added '<li><a href="#-polygon">Polygon</a></li>' line of code
not needed
=> Added "polygon" url in index section

README.md
Created Flow blockchain section with intro and resources
added section after polygon section
not needed
=> added Flow Blockchain section with resources and intro

FREE Web3 Resources (2).html, index.html
1. Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.
<meta charset="UTF-8" />↩
2. Error:  A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the 
value IE=edge.
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
**As the Google Chrome Frame plugin was discontinued on February 25, 2014, this is longer supported**
4. The type attribute is unnecessary for JavaScript resources.
<script ↩    src="//cdn.jsdelivr.net/npm/docsify-darklight-theme@latest/dist/index.min.js"↩    type="text/javascript">
The type attribute in JavaScript is optional since the introduction of HTML5 brought some new improvements. JavaScript became the default language for HTML5 and modern browsers.
5. …
=> Removed all warning and some errors from index.html and  FREE Web3 Resources (2).html

twitter-posts.md
=> docusaurus

docusaurus.config.js
=> fix: replace social links

docs/blockchains/blockchains.md
=> added monero in blockchains

docusaurus.config.js
Closes #312 
Removed the Stack Overflow link in the footer in docusaurus.config.js file
=> Remove the Stack Overflow link in the footer

README.md
Add an 's' to Ether.js for correct spelling
- [x ] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
=> Fix typo in Ether.js to Ethers.js

code-snippets/functsolidity.sol
Removed unnecessary spaces in the code.
Fixed an error in the getName() function (It was being called twice while returning both the age and name). 
Fixed the general layout of the code as per general code conventions
=> Refactor functsolidity code for easy readability

code-snippets/PiggyBank.sol
Refined the code by removing spaces, adding comments and making minor changes.
=> refactored piggyBank for improved readability

code-snippets/functsolidity.sol
Added two functions `changeName()` and `changeAge()` in functsolidity.sol to allow users to change the variables to arbitrary values.
=> Add a way to change name and age in functsolidity.sol.

README.md
Hey, just found a typo issue, here's the PR to fix it 🙏
👇
=> fix newline before Francesco YT Channel

FREE Web3 Resources (2).html
=> I added a free polygon bootcamp

docs/blogs/blogs.md, yarn.lock
=> Remove duplicate Blog link

docusaurus.config.js
=> Fixed some minor page issues

docs/roadmaps/blockchain-roadmaps.md
Closes #328
I have added a useful YouTube video in the list of blockchain roadmaps!
=> Add a YouTube Video

docusaurus.config.js
=> fix footer

docs/learning-platforms/platforms.md
- Added DApp World platform in the list
Proposed changes as per @tobySolutions instructions
=> Added web3 learning platform

src/css/custom.css, yarn.lock
ADD A CUSTOM SCROLL BAR ACROSS WEBSITE
A scroll bar matching the colors of the website looks nice to me, as mentioned in issue #344 
I have already attached the screenshots of how it will look in the issue
Closes #344
=> Add custom scroll-bar across website

docusaurus.config.js, package-lock.json, yarn.lock
=> add freeweb3 favicon

docs/polygon/polygon.md
Full Course on Polygon Development | Build Blockchain Apps on Polygon
=> ADDED Full Course on Polygon Development

src/components/HomepageFeatures/index.js, src/css/custom.css, src/pages/index.js, src/pages/markdown-page.md
[Screencast from 01-14-2023 01:38:06 AM.webm](https://user-images.githubusercontent.com/96334363/212441752-0d80a13a-dc34-4dc3-8052-8a5883fe1851.webm)
Please review accordingly Maintainers!! @tobySolutions, @FrancescoXX!!
Fixed issue #346.
=> feat: change entire site's UI

src/css/custom.css
=> feat: remove background photo

docs/how-to-start-blockchain/how-to-start-blockchain.md
=> Fix: typos

README.md
@tobySolutions Made the necessary changes
Thanks for assigning me!
Fixes #369
=> Improved README.md formatting

.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
=> Update  PULL_REQUEST_TEMPLATE.md

src/components/HomepageFeatures/index.js, src/css/custom.css
=> feat: change site color to match 4c

src/css/custom.css
=> feat: fix text contrast of light mode with background

docs/learning-platforms/platforms.md
useWeb3 is a platform for developers to explore and learn from tutorials, courses, books, videos or code challenges and start building!
=> Added useWeb3 in Learning Platforms

docs/Project Ideas/project-ideas.md
Added Projects Ideas to Become a Web3 and Blockchain Master - Beginner to Expert
=> Added 23 new Projects Ideas

docusaurus.config.js
I have edited the announcement banner text to say 'Are you content creator, Join the community'. The text has now been edited to match that.
=> feat: change the announcement banner text

docusaurus.config.js, package-lock.json, src/css/custom.css, yarn.lock
- <h3>Footer elements was not in center</h3>
- <h3>Footer elements are set to center</h3>
=> Footer section has been set to center successfully

docs/Project Ideas/project-ideas.md
Added Web3 Projects with description what things you will learn while building these projects . Added Tutorial Source for references. Will add the remaining source soon.
=> Added Web3 Projects with Source

src/css/custom.css
=> feat(light-mode): fix issue #394

src/css/custom.css, yarn.lock
**Closes #395**
We were facing an issue with the responsiveness, so what I did was whenever max-width of the display hits 500px or less, our title would adjust its font size. Now it's looking more responsive, and the search bar is not overlapping the title.
=> feat: Navbar Fix

src/css/custom.css
Fixed the outline margin error that was coming in search box
Fixes issue #400.
=> fix: outline

src/components/HomepageFeatures/index.js, src/css/custom.css
=> fix: fixed inconsistent spacing

src/css/custom.css
i have made some changes to the light mode but need some feedback.is the gray text looking okay or it should be more dark?
and should i also change the color of the navbar and footer in light mode??
=> feat: light mode changes

src/pages/index.module.css
Changed background color and text color
**Before:**
**After:**
issue #418
=> banner section background color changed #418

docusaurus.config.js
=> [Feat]: removed the "Free Web3 Resources" title #427

docs/blockchains/blockchainArchitecture.md
=>  [Feat]: removed section afrom blockArchitecture #417

docs/tutorials/_category_.json, docs/tutorials/courses.md
=>  [Bug]: renamed "Tutorials" to "Courses" issue#424 

src/components/HomepageFeatures/index.js
=> Updated invalid "blockchains" link

docs/courses/learnweb3.md
Fix the image size on website and added learnweb3 Github link
=> Fix Image size

docs/courses/cryptozombies.md
In previous docs link to the cryptozombies was not provided. I added Cryptozombies link to the docs.
=> Update cryptozombies.md added link

docs/courses/alchemy.md, docs/courses/cryptozombies.md
Detailed alchemy definition and added relevant links to course
=> Detailed definition & Links
